/* =============================================================================
 * Chord.types.d.ts — GENERATED by RoomKit schema type generation.
 * DO NOT EDIT BY HAND.
 *
 * This is the frontend contract emitted from the room config: primary model,
 * composed plugin operations, query results, routes, and launch envelope.
 * ========================================================================== */


export namespace Chord {
  export type Role = "guest" | "member" | "moderator" | "admin" | "owner";
  export type ChannelId = string & { readonly __brand: "ChannelId" };
  export type MessageId = string & { readonly __brand: "MessageId" };
  export type RoleId = string & { readonly __brand: "RoleId" };
  export type RoomId = string & { readonly __brand: "RoomId" };
  export type MemberId = string & { readonly __brand: "MemberId" };
  export type ThreadId = string & { readonly __brand: "ThreadId" };
  export type CommentId = string & { readonly __brand: "CommentId" };
  export type EmbedId = string & { readonly __brand: "EmbedId" };
  export type ShareId = string & { readonly __brand: "ShareId" };
  export type Reactions = Record<string, MemberId[]>;
  export type ScopeType = "channel" | (string & {});
  export interface ScopeRef { scopeType: ScopeType; scopeId: string; }
  export type RoleAccessGrant = "editor" | "readonly";
  export type RoomRoleAccess = Record<RoleId, RoleAccessGrant>;
  export type AccessLevel = "hidden" | RoleAccessGrant;
  export type PresenceStatus = "online" | "idle" | "dnd" | "offline" | (string & {});
  export interface MediaFlags { audio?: boolean; video?: boolean; screen?: boolean; }
  export interface MessageEmbed { id?: EmbedId; url: string; provider?: string; kind?: string; title?: string; thumbnailUrl?: string; renderMode?: string; }
  export interface Member { id?: MemberId; memberId?: MemberId; name?: string; displayName?: string; role?: Role | (string & {}); status?: string; avatarUrl?: string; revokedAt?: number | null; bannedAt?: number | null; }
  /** From the mediaRooms plugin. */
  export interface MediaRoomParticipant { memberId: MemberId; name?: string; media?: MediaFlags; joinedAt?: number; }
  /** From the mediaRooms plugin. */
  export interface MediaRoom { id: RoomId; name: string; group: string | null; allowsVideo: boolean; scopeType?: ScopeType; scopeId?: string; roleAccess: RoomRoleAccess; locked: boolean; spotlightMemberId?: MemberId | null; archivedAt: number | null; participants: Record<MemberId, MediaRoomParticipant>; participantCount: number; createdBy?: MemberId; createdAt?: number; }

  /** From the presence plugin. */
  export interface PresenceMember { memberId: MemberId; name?: string; status: PresenceStatus; activity: string | null; location: string | null; updatedAt?: number; lastPingAt?: number; visible?: boolean; avatarUrl?: string; }

  /** From the comments plugin. */
  export interface CommentThread { id: ThreadId; scopeType: ScopeType; scopeId: string; title: string | null; resolved: boolean; createdAt: number; lastCommentAt?: number; archivedAt: number | null; }
  /** From the comments plugin. */
  export interface Comment { id: CommentId; threadId: ThreadId; scopeType?: ScopeType; scopeId?: string; parentId?: CommentId | null; body: string; authorId: MemberId; authorName?: string; createdAt: number; deletedAt: number | null; reactions: Reactions; }

  /** From the embeds plugin. */
  export interface Embed { id: EmbedId; scopeType: ScopeType; scopeId: string; url: string; provider?: string; kind?: string; title?: string; note: string | null; addedBy?: MemberId; addedByName?: string; addedAt: number; removedAt: number | null; }

  /** From the reactions plugin. */
  export interface ScopedReaction { scopeType: ScopeType; scopeId: string; reactions: Reactions; updatedAt?: number; }

  /** From the screenShare plugin. */
  export interface ScreenShare { id: ShareId; scopeType?: ScopeType; scopeId?: string; roomId: RoomId | null; title: string | null; presenterId: MemberId; presenterName?: string; startedAt: number; stoppedAt: number | null; stoppedBy?: MemberId; }

  /** From roomkit.core direct messages. */
  export interface DirectThread { id: ThreadId; protocol?: string; userIds: MemberId[]; topicKey?: string; topic: string | null; createdAt: number; archivedAt: number | null; }
  /** From roomkit.core direct messages. */
  export interface DirectMessage { id: MessageId; protocol?: string; threadId: ThreadId; userIds?: MemberId[]; topicKey?: string; authorId: MemberId; body: string; reactions: Reactions; embeds: MessageEmbed[]; replyToId?: MessageId | null; pinnedAt?: number | null; pinnedBy?: MemberId | null; editedAt?: number | null; deletedAt?: number | null; deletedBy?: MemberId | null; createdAt: number; encrypted?: boolean; }
  export interface Actor { memberId: MemberId; deviceId: string; role: Role | (string & {}); displayName?: string; avatar?: string; avatarUrl?: string; profileImageUrl?: string; }
  export interface Activity { id: string; operationId?: string; actorId?: MemberId; actorName?: string; message: string; createdAt?: number; }
  /**
   * From primary model collection `channels`.
   */
  export interface Channel {
    archivedAt: null | number;
    createdAt: number;
    createdBy: MemberId;
    group: null | string;
    id: ChannelId;
    name: string;
    topic: null | string;
    updatedAt?: number;
  }
  /**
   * From primary model collection `memberRoles`.
   */
  export interface MemberRole {
    assignedAt: number;
    assignedBy: MemberId;
    displayName: null | string;
    id: string;
    memberId: MemberId;
    roleId: RoleId | null;
    roleIds: RoleId[];
  }
  /**
   * From primary model collection `messages`.
   */
  export interface Message {
    authorId: MemberId;
    body: string;
    channelId: ChannelId;
    createdAt: number;
    deletedAt: null | number;
    deletedBy: MemberId | null;
    editedAt: null | number;
    embeds: MessageEmbed[];
    id: MessageId;
    pinnedAt: null | number;
    pinnedBy: MemberId | null;
    reactions: Reactions;
    replyToId: MessageId | null;
  }
  /**
   * From primary model collection `roleDefinitions`.
   */
  export interface RoleDefinition {
    archivedAt: null | number;
    archivedBy?: MemberId;
    color: null | string;
    createdAt?: number;
    createdBy?: MemberId;
    description: null | string;
    id: RoleId;
    name: string;
    rank: number;
    systemRole: boolean;
    updatedAt?: number;
    updatedBy?: MemberId;
  }
  export interface State {
    activity: Activity[];
    channels: Channel[];
    comments: Record<CommentId, Comment>;
    commentThreads: Record<ThreadId, CommentThread>;
    directMessages: Record<MessageId, DirectMessage>;
    directThreads: Record<ThreadId, DirectThread>;
    embeds: Record<EmbedId, Embed>;
    memberRoles: Record<MemberId, MemberRole>;
    members: Record<MemberId, Member>;
    messages: Record<MessageId, Message>;
    presence: Record<MemberId, PresenceMember>;
    reactions: Record<string, ScopedReaction>;
    roleDefinitions: Record<RoleId, RoleDefinition>;
    rooms: MediaRoom[];
    screenShares: Record<ShareId, ScreenShare>;
  }
  export interface DirectMessageThread { thread: DirectThread; messages: DirectMessage[]; }
  export interface Actions {
    /**
     * Requires `moderator` role.
     * channelId: string, <= 200
     */
    channelArchive: { channelId: ChannelId };
    /**
     * Requires `admin` role.
     * name: string, <= 80
     * topic: string, <= 240, nullable, omit to leave unchanged; null to clear
     * group: string, <= 80, nullable, omit to leave unchanged; null to clear
     */
    channelCreate: { name: string; topic?: null | string; group?: null | string };
    /**
     * Requires `moderator` role.
     * channelId: string, <= 200
     * name: string, <= 80, nullable, omit to leave unchanged; null to clear
     * topic: string, <= 240, nullable, omit to leave unchanged; null to clear
     * group: string, <= 80, nullable, omit to leave unchanged; null to clear
     */
    channelRename: { channelId: ChannelId; name?: null | string; topic?: null | string; group?: null | string };
    /**
     * Requires `admin` role.
     * memberId: string, <= 120
     * roleId: string, <= 80, nullable, omit to leave unchanged; null to clear
     * roleIds: array
     * displayName: string, <= 120, nullable, omit to leave unchanged; null to clear
     */
    memberRoleAssign: { memberId: MemberId; roleId?: RoleId | null; roleIds?: RoleId[]; displayName?: null | string };
    /**
     * Requires `member` role.
     * messageId: string, <= 200
     */
    messageDelete: { messageId: MessageId };
    /**
     * Requires `member` role.
     * messageId: string, <= 200
     * body: string, <= 4000
     * embeds: array
     */
    messageEdit: { messageId: MessageId; body: string; embeds?: MessageEmbed[] };
    /**
     * Requires `moderator` role.
     * messageId: string, <= 200
     */
    messagePin: { messageId: MessageId };
    /**
     * Requires `member` role.
     * messageId: string, <= 200
     * emoji: string, <= 64
     */
    messageReact: { messageId: MessageId; emoji: string };
    /**
     * Requires `member` role.
     * channelId: string, <= 200
     * replyToId: string, <= 200
     * body: string, <= 4000
     */
    messageReply: { channelId: ChannelId; replyToId: MessageId; body: string };
    /**
     * Requires `member` role.
     * channelId: string, <= 200
     * body: string, <= 4000
     * embeds: array
     */
    messageSend: { channelId: ChannelId; body: string; embeds?: MessageEmbed[] };
    /**
     * Requires `moderator` role.
     * messageId: string, <= 200
     */
    messageUnpin: { messageId: MessageId };
    /**
     * Requires `admin` role.
     * roleId: string, <= 80
     */
    roleArchive: { roleId: RoleId };
    /**
     * Requires `admin` role.
     * roleId: string, <= 80
     * name: string, <= 80
     * description: string, <= 240, nullable, omit to leave unchanged; null to clear
     * color: string, <= 40, nullable, omit to leave unchanged; null to clear
     */
    roleCreate: { roleId: RoleId; name: string; description?: null | string; color?: null | string };
    /**
     * Requires `admin` role.
     * roleId: string, <= 80
     * name: string, <= 80, nullable, omit to leave unchanged; null to clear
     * description: string, <= 240, nullable, omit to leave unchanged; null to clear
     * color: string, <= 40, nullable, omit to leave unchanged; null to clear
     */
    roleUpdate: { roleId: RoleId; name?: null | string; description?: null | string; color?: null | string };
    /**
     * Requires `member` role.
     * body: string
     * threadId: string
     * scopeType: string
     * scopeId: string
     * parentId: string
     */
    commentsAdd: { body: string; threadId?: ThreadId; parentId?: CommentId } & Partial<ScopeRef>;
    /**
     * Requires `member` role.
     * commentId: string
     * reason: string
     */
    commentsDelete: { commentId: CommentId; reason?: string };
    /**
     * Requires `member` role.
     * commentId: string
     * body: string
     */
    commentsEdit: { commentId: CommentId; body: string };
    /**
     * Requires `member` role.
     * commentId: string
     * emoji: string
     */
    commentsReact: { commentId: CommentId; emoji: string };
    /**
     * Requires `moderator` role.
     * threadId: string
     * resolved: string
     */
    commentsResolve: { threadId: ThreadId; resolved?: boolean };
    /**
     * Requires `member` role.
     * scopeType: string
     * scopeId: string
     * title: string
     * visibility: string
     */
    commentsThreadCreate: { title?: string; visibility?: string } & ScopeRef;
    /**
     * Requires `member` role.
     * memberId: string
     */
    presenceClear: { memberId?: MemberId };
    /**
     * Requires `member` role.
     * status: string
     */
    presencePing: { status?: PresenceStatus };
    /**
     * Requires `member` role.
     * status: string
     * activity: string
     * location: string
     */
    presenceUpdate: { status: PresenceStatus; activity?: string; location?: string };
    /**
     * Requires `moderator` role.
     * roomId: string, <= 200
     */
    mediaRoomArchive: { roomId: RoomId };
    /**
     * Requires `moderator` role.
     * name: string, <= 100
     * allowsVideo: boolean
     * group: string, <= 80, nullable, omit to leave unchanged; null to clear
     * scopeType: string, <= 80
     * scopeId: string, <= 160
     * roleAccess: record
     */
    mediaRoomCreate: { name: string; allowsVideo?: boolean; group?: null | string; roleAccess?: RoomRoleAccess } & Partial<ScopeRef>;
    /**
     * Requires `member` role.
     * roomId: string, <= 200
     * media: object
     */
    mediaRoomJoin: { roomId: RoomId; media?: MediaFlags };
    /**
     * Requires `member` role.
     * roomId: string, <= 200
     */
    mediaRoomLeave: { roomId: RoomId };
    /**
     * Requires `moderator` role.
     * roomId: string, <= 200
     * locked: boolean
     * allowsVideo: boolean
     * spotlightMemberId: string, <= 120
     * name: string, <= 100
     * group: string, <= 80, nullable, omit to leave unchanged; null to clear
     * roleAccess: record
     */
    mediaRoomUpdate: { roomId: RoomId; locked?: boolean; allowsVideo?: boolean; spotlightMemberId?: MemberId; name?: string; group?: null | string; roleAccess?: RoomRoleAccess };
    /**
     * Requires `member` role.
     * scopeType: string
     * scopeId: string
     * roomId: string
     * title: string
     */
    screenshareStart: { roomId?: RoomId; title?: string } & ScopeRef;
    /**
     * Requires `member` role.
     * shareId: string
     */
    screenshareStop: { shareId: ShareId };
    /**
     * Requires `member` role.
     * scopeType: string
     * scopeId: string
     * url: string
     * title: string
     * provider: string
     * note: string
     */
    embedAdd: { url: string; title?: string; provider?: string; note?: string } & ScopeRef;
    /**
     * Requires `member` role.
     * embedId: string
     */
    embedRemove: { embedId: EmbedId };
    /**
     * Requires `member` role.
     * scopeType: string
     * scopeId: string
     * emoji: string
     */
    reactionToggle: { emoji: string } & ScopeRef;
    /**
     * Requires `member` role.
     * userIds: array
     * body: string
     * topicKey: string
     */
    directMessageSend: { userIds: MemberId[]; body: string; topicKey?: string };
  }
  export type ActionName = keyof Actions;
  export type ActionPayload<K extends ActionName> = Actions[K];
  export type OperationType = {
    channelArchive: "channel.archive";
    channelCreate: "channel.create";
    channelRename: "channel.rename";
    memberRoleAssign: "member.role.assign";
    messageDelete: "message.delete";
    messageEdit: "message.edit";
    messagePin: "message.pin";
    messageReact: "message.react";
    messageReply: "message.reply";
    messageSend: "message.send";
    messageUnpin: "message.unpin";
    roleArchive: "role.archive";
    roleCreate: "role.create";
    roleUpdate: "role.update";
    commentsAdd: "comments.add";
    commentsDelete: "comments.delete";
    commentsEdit: "comments.edit";
    commentsReact: "comments.react";
    commentsResolve: "comments.resolve";
    commentsThreadCreate: "comments.thread.create";
    presenceClear: "presence.clear";
    presencePing: "presence.ping";
    presenceUpdate: "presence.update";
    mediaRoomArchive: "media.room.archive";
    mediaRoomCreate: "media.room.create";
    mediaRoomJoin: "media.room.join";
    mediaRoomLeave: "media.room.leave";
    mediaRoomUpdate: "media.room.update";
    screenshareStart: "screenshare.start";
    screenshareStop: "screenshare.stop";
    embedAdd: "embed.add";
    embedRemove: "embed.remove";
    reactionToggle: "reaction.toggle";
    directMessageSend: "dm.message";
  };
  export interface Queries {
    channelSummary: Channel[];
    roomDirectory: MediaRoom[];
    onlineMembers: PresenceMember[];
  }
  export type QueryName = keyof Queries;
  export interface QueryInput {
    channelSummary: void;
    roomDirectory: void;
    onlineMembers: void;
  }
  export type RoutePath = "/" | "/dms" | "/rooms";
  export type RouteComponent = "ChatRoomPage" | "DirectMessagesPage" | "MediaRoomsPage";
  export interface Core {
    sendPresence(input: { status: PresenceStatus; activity?: string; at?: number }): Promise<boolean>;
  }
  export interface LaunchEnvelope { room?: { id?: string; name?: string }; actor?: Actor; credentialGrant?: { credentialId?: string }; initialState?: State; }
}
export interface Chord {
  State: Chord.State;
  Actions: Chord.Actions;
  Queries: Chord.Queries;
  QueryInput: Chord.QueryInput;
  Actor: Chord.Actor;
  Core: Chord.Core;
  LaunchEnvelope: Chord.LaunchEnvelope;
  DirectMessageThread: Chord.DirectMessageThread;
}
