/* =============================================================================
 * Chord.types.d.ts — GENERATED by RoomKit schema type generation.
 * DO NOT EDIT BY HAND.
 *
 * This is the frontend contract emitted from the room config: primary model,
 * composed plugin operations, query results, routes, and launch envelope.
 * ========================================================================== */


export namespace Chord {
  export type Role = "guest" | "member" | "moderator" | "admin" | "owner";
  export interface Actor { memberId: string; deviceId?: string; role: Role | string; displayName?: string; avatar?: string; avatarUrl?: string; profileImageUrl?: string; [key: string]: unknown; }
  export interface Activity { id: string; operationId?: string; actorId?: string; actorName?: string; message: string; createdAt?: number; [key: string]: unknown; }
  export interface MediaRoomParticipant { memberId: string; name?: string; media?: { audio?: boolean; video?: boolean; screen?: boolean }; joinedAt?: number; }
  export interface MediaRoom { id: string; name: string; group?: string | null; allowsVideo?: boolean; scopeType?: string; scopeId?: string; roleAccess?: Record<string, "editor" | "readonly" | "hidden">; locked?: boolean; spotlightMemberId?: string; archivedAt?: number; participants?: Record<string, MediaRoomParticipant>; participantCount?: number; createdBy?: string; createdAt?: number; }
  export interface PresenceMember { memberId: string; name?: string; status?: string; activity?: string | null; location?: string | null; updatedAt?: number; lastPingAt?: number; visible?: boolean; }
  export interface CommentThread { id: string; scopeType?: string; scopeId?: string; title?: string | null; resolved?: boolean; createdAt?: number; lastCommentAt?: number; archivedAt?: number | null; }
  export interface Comment { id: string; threadId?: string; scopeType?: string; scopeId?: string; body: string; authorId?: string; authorName?: string; createdAt?: number; deletedAt?: number | null; reactions?: Record<string, string[]>; }
  export interface Embed { id?: string; scopeType?: string; scopeId?: string; url: string; provider?: string; kind?: string; title?: string; note?: string | null; addedBy?: string; addedByName?: string; addedAt?: number; removedAt?: number | null; }
  export interface ScopedReaction { scopeType?: string; scopeId?: string; reactions: Record<string, string[]>; updatedAt?: number; }
  export interface ScreenShare { id: string; scopeType?: string; scopeId?: string; roomId?: string | null; title?: string | null; presenterId?: string; presenterName?: string; startedAt?: number; stoppedAt?: number | null; stoppedBy?: string; }
  export interface Attachment { id: string; scopeType?: string; scopeId?: string; url?: string; title?: string; mimeType?: string | null; sizeBytes?: number | null; provider?: string | null; note?: string | null; addedAt?: number; removedAt?: number | null; }
  export interface Label { id: string; name: string; color?: string | null; description?: string | null; archivedAt?: number | null; }
  export interface Checklist { id: string; scopeType?: string; scopeId?: string; title?: string; items?: Array<{ id: string; text: string; completed?: boolean; completedAt?: number | null }>; archivedAt?: number | null; }
  export interface CalendarEvent { id: string; scopeType?: string; scopeId?: string; title: string; startsAt?: number; endsAt?: number | null; location?: string | null; description?: string | null; cancelledAt?: number | null; }
  export interface LocationPin { id: string; scopeType?: string; scopeId?: string; label?: string; lat?: number; lng?: number; createdAt?: number; removedAt?: number | null; }
  export interface Channel {
    archivedAt: null | number;
    createdAt: number;
    createdBy: string;
    group?: null | string;
    id: string;
    name: null | string;
    topic?: null | string;
    updatedAt?: number;
  }
  export interface MemberRole {
    assignedAt: number;
    assignedBy: string;
    displayName?: null | string;
    id: string;
    memberId: string;
    roleId?: null | string;
    roleIds?: string[];
  }
  export interface Message {
    authorId: string;
    body: string;
    channelId: string;
    createdAt: number;
    deletedAt?: null | number;
    deletedBy?: string;
    editedAt?: null | number;
    embeds?: unknown[];
    id: string;
    pinnedAt?: null | number;
    pinnedBy?: null | string;
    reactions: Record<string, unknown>;
    replyToId?: string;
  }
  export interface RoleDefinition {
    archivedAt: null | number;
    archivedBy?: string;
    color?: null | string;
    createdAt?: number;
    createdBy?: string;
    description?: null | string;
    id: string;
    name: null | string;
    rank: number;
    systemRole: boolean;
    updatedAt?: number;
    updatedBy?: string;
  }
  export interface CommentsPluginState {
    [key: string]: unknown;
  }
  export interface PresencePluginState {
    [key: string]: unknown;
  }
  export interface MediaRoomsPluginState {
    [key: string]: unknown;
  }
  export interface ScreenSharePluginState {
    [key: string]: unknown;
  }
  export interface EmbedsPluginState {
    [key: string]: unknown;
  }
  export interface ReactionsPluginState {
    [key: string]: unknown;
  }
  export interface Plugins {
    "com.roomkit.examples.plugins.comments": CommentsPluginState;
    "com.roomkit.examples.plugins.presence": PresencePluginState;
    "com.roomkit.examples.plugins.media-rooms": MediaRoomsPluginState;
    "com.roomkit.examples.plugins.screen-share": ScreenSharePluginState;
    "com.roomkit.examples.plugins.embeds": EmbedsPluginState;
    "com.roomkit.examples.plugins.reactions": ReactionsPluginState;
  }
  export interface PluginAliases {
    comments: Plugins["com.roomkit.examples.plugins.comments"];
    presence: Plugins["com.roomkit.examples.plugins.presence"];
    mediaRooms: Plugins["com.roomkit.examples.plugins.media-rooms"];
    screenShare: Plugins["com.roomkit.examples.plugins.screen-share"];
    embeds: Plugins["com.roomkit.examples.plugins.embeds"];
    reactions: Plugins["com.roomkit.examples.plugins.reactions"];
  }
  export interface State {
    activity: Activity[];
    channels: Channel[];
    memberRoles: Record<string, MemberRole>;
    messages: Record<string, Message>;
    plugins: Plugins;
    roleDefinitions: Record<string, RoleDefinition>;
  }
  export interface Operations {
    "channel.archive": { channelId: string };
    "channel.create": { name: string; topic?: null | string; group?: null | string };
    "channel.rename": { channelId: string; name?: null | string; topic?: null | string; group?: null | string };
    "member.role.assign": { memberId: string; roleId?: null | string; roleIds?: string[]; displayName?: null | string };
    "message.delete": { messageId: string };
    "message.edit": { messageId: string; body: string; embeds?: unknown[] };
    "message.pin": { messageId: string };
    "message.react": { messageId: string; emoji: string };
    "message.reply": { channelId: string; replyToId: string; body: string };
    "message.send": { channelId: string; body: string; embeds?: unknown[] };
    "message.unpin": { messageId: string };
    "role.archive": { roleId: string };
    "role.create": { roleId: string; name: string; description?: null | string; color?: null | string };
    "role.update": { roleId: string; name?: null | string; description?: null | string; color?: null | string };
  }
  export type OpName = keyof Operations;
  export type Payload<K extends OpName> = Operations[K];
  export interface Queries {
    channelSummary: Channel[];
    roomDirectory: MediaRoom[];
    onlineMembers: Actor[];
  }
  export type QueryName = keyof Queries;
  export type RoutePath = "/" | "/dms" | "/rooms";
  export type RouteComponent = "ChatRoomPage" | "DirectMessagesPage" | "MediaRoomsPage";
  export interface LaunchEnvelope { room?: { id?: string; name?: string }; actor?: Actor; credentialGrant?: { credentialId?: string }; initialState?: State; }
  export interface HostResult { ok: boolean; state?: State; reason?: string; operation?: unknown; }
  export interface Client { state: State; status: "connecting" | "connected" | "saving" | "offline" | "error"; dispatch<K extends OpName>(type: K, payload: Operations[K]): Promise<HostResult>; query<K extends QueryName>(name: K, input?: Record<string, unknown>): Queries[K]; }
}
