/* =============================================================================
 * Chord.types.d.ts — GENERATED by RoomKit schema type generation.
 * DO NOT EDIT BY HAND.
 *
 * This is the frontend contract emitted from the room config: primary model,
 * composed plugin operations, query results, routes, and launch envelope.
 * ========================================================================== */


export namespace Chord {
  export type Role = "guest" | "member" | "moderator" | "admin" | "owner";
  export type ChannelId = string;
  export type MessageId = string;
  export type RoleId = string;
  export type RoomId = string;
  export type MemberId = string;
  export type ThreadId = string;
  export type CommentId = string;
  export type EmbedId = string;
  export type ShareId = string;
  export type Reactions = Record<string, MemberId[]>;
  export type ScopeType = "channel" | (string & {});
  export interface ScopeRef { scopeType: ScopeType; scopeId: string; }
  export type RoleAccessGrant = "editor" | "readonly";
  export type RoomRoleAccess = Record<RoleId, RoleAccessGrant>;
  export type AccessLevel = "hidden" | RoleAccessGrant;
  export type ScopedRole = "none" | "viewer" | "editor" | "moderator" | "admin" | "owner";
  export type PresenceStatus = "online" | "idle" | "dnd" | "offline" | (string & {});
  export interface MediaFlags { audio?: boolean; video?: boolean; screen?: boolean; }
  export interface MessageEmbed { id?: EmbedId; url: string; provider?: string; kind?: string; title?: string; thumbnailUrl?: string; renderMode?: string; }
  export interface Member { id?: MemberId; memberId?: MemberId; name?: string; displayName?: string; role?: Role | (string & {}); status?: string; avatarUrl?: string; revokedAt?: number | null; bannedAt?: number | null; }
  export interface MediaRoomParticipant { memberId: MemberId; name?: string; media?: MediaFlags; joinedAt?: number; }
  export interface MediaRoom { id: RoomId; name: string; group: string | null; allowsVideo: boolean; scopeType?: ScopeType; scopeId?: string; roleAccess: RoomRoleAccess; locked: boolean; spotlightMemberId?: MemberId | null; archivedAt: number | null; participants: Record<MemberId, MediaRoomParticipant>; participantCount: number; createdBy?: MemberId; createdAt?: number; }

  export interface PresenceMember { memberId: MemberId; name?: string; status: PresenceStatus; activity: string | null; location: string | null; updatedAt?: number; lastPingAt?: number; visible?: boolean; avatarUrl?: string; }

  export interface CommentThread { id: ThreadId; scopeType: ScopeType; scopeId: string; title: string | null; resolved: boolean; createdAt: number; lastCommentAt?: number; archivedAt: number | null; }
  export interface Comment { id: CommentId; threadId: ThreadId; scopeType?: ScopeType; scopeId?: string; parentId?: CommentId | null; body: string; authorId: MemberId; authorName?: string; createdAt: number; deletedAt: number | null; reactions: Reactions; }

  export interface Embed { id: EmbedId; scopeType: ScopeType; scopeId: string; url: string; provider?: string; kind?: string; title?: string; note: string | null; addedBy?: MemberId; addedByName?: string; addedAt: number; removedAt: number | null; }

  export interface ScopedReaction { scopeType: ScopeType; scopeId: string; reactions: Reactions; updatedAt?: number; }

  export interface ScreenShare { id: ShareId; scopeType?: ScopeType; scopeId?: string; roomId: RoomId | null; title: string | null; presenterId: MemberId; presenterName?: string; startedAt: number; stoppedAt: number | null; stoppedBy?: MemberId; }

  export interface DirectThread { id: ThreadId; protocol?: string; userIds: MemberId[]; topicKey?: string; topic: string | null; createdAt: number; archivedAt: number | null; }
  export interface DirectMessage { id: MessageId; protocol?: string; threadId: ThreadId; userIds?: MemberId[]; topicKey?: string; authorId: MemberId; body: string; reactions: Reactions; embeds: MessageEmbed[]; replyToId?: MessageId | null; pinnedAt?: number | null; pinnedBy?: MemberId | null; editedAt?: number | null; deletedAt?: number | null; deletedBy?: MemberId | null; createdAt: number; encrypted?: boolean; }
  export interface Actor { memberId: MemberId; deviceId: string; role: Role | (string & {}); displayName?: string; avatar?: string; avatarUrl?: string; profileImageUrl?: string; }
  export interface Activity { id: string; operationId?: string; actorId?: MemberId; actorName?: string; message: string; createdAt?: number; }
  export interface Channel {
    archivedAt: null | number;
    createdAt: number;
    createdBy: MemberId;
    group: null | string;
    id: ChannelId;
    name: string;
    topic: null | string;
    updatedAt?: number;
  }
  export interface MemberRole {
    assignedAt: number;
    assignedBy: MemberId;
    displayName: null | string;
    id: string;
    memberId: MemberId;
    roleId: RoleId | null;
    roleIds: RoleId[];
  }
  export interface Message {
    authorId: MemberId;
    body: string;
    channelId: ChannelId;
    createdAt: number;
    deletedAt: null | number;
    deletedBy: MemberId | null;
    editedAt: null | number;
    embeds: MessageEmbed[];
    id: MessageId;
    pinnedAt: null | number;
    pinnedBy: MemberId | null;
    reactions: Reactions;
    replyToId: MessageId | null;
  }
  export interface RoleDefinition {
    archivedAt: null | number;
    archivedBy?: MemberId;
    color: null | string;
    createdAt?: number;
    createdBy?: MemberId;
    description: null | string;
    id: RoleId;
    name: string;
    rank: number;
    systemRole: boolean;
    updatedAt?: number;
    updatedBy?: MemberId;
  }
  export interface CommentsPluginState {
    activity: Activity[];
    comments: Record<CommentId, Comment>;
    threads: Record<ThreadId, CommentThread>;
  }
  export interface PresencePluginState {
    activity: Activity[];
    members: Record<MemberId, PresenceMember>;
  }
  export interface MediaRoomsPluginState {
    activity: Activity[];
    rooms: Record<RoomId, MediaRoom>;
  }
  export interface ScreenSharePluginState {
    activity: Activity[];
    shares: Record<ShareId, ScreenShare>;
  }
  export interface EmbedsPluginState {
    activity: Activity[];
    embeds: Record<EmbedId, Embed>;
  }
  export interface ReactionsPluginState {
    activity: Activity[];
    reactions: Record<string, ScopedReaction>;
  }
  export interface State {
    activity: Activity[];
    channels: Channel[];
    comments: CommentsPluginState;
    directMessages: Record<MessageId, DirectMessage>;
    directThreads: Record<ThreadId, DirectThread>;
    embeds: Record<EmbedId, Embed>;
    memberRoles: Record<MemberId, MemberRole>;
    members: Record<MemberId, Member>;
    messages: Record<MessageId, Message>;
    presence: Record<MemberId, PresenceMember>;
    reactions: Record<string, ScopedReaction>;
    roleDefinitions: Record<RoleId, RoleDefinition>;
    rooms: MediaRoom[];
    screenShares: Record<ShareId, ScreenShare>;
  }
  export interface DirectMessageThread { thread: DirectThread; messages: DirectMessage[]; }
  export interface Actions {
    channelArchive: { channelId: ChannelId };
    channelCreate: { name: string; topic?: null | string; group?: null | string };
    channelRename: { channelId: ChannelId; name?: null | string; topic?: null | string; group?: null | string };
    memberRoleAssign: { memberId: MemberId; roleId?: RoleId | null; roleIds?: RoleId[]; displayName?: null | string };
    messageDelete: { messageId: MessageId };
    messageEdit: { messageId: MessageId; body: string; embeds?: MessageEmbed[] };
    messagePin: { messageId: MessageId };
    messageReact: { messageId: MessageId; emoji: string };
    messageReply: { channelId: ChannelId; replyToId: MessageId; body: string };
    messageSend: { channelId: ChannelId; body: string; embeds?: MessageEmbed[] };
    messageUnpin: { messageId: MessageId };
    roleArchive: { roleId: RoleId };
    roleCreate: { roleId: RoleId; name: string; description?: null | string; color?: null | string };
    roleUpdate: { roleId: RoleId; name?: null | string; description?: null | string; color?: null | string };
    commentsAdd: { body: string; threadId?: ThreadId; parentId?: CommentId } & Partial<ScopeRef>;
    commentsDelete: { commentId: CommentId; reason?: string };
    commentsEdit: { commentId: CommentId; body: string };
    commentsReact: { commentId: CommentId; emoji: string };
    commentsResolve: { threadId: ThreadId; resolved?: boolean };
    commentsThreadCreate: { title?: string; visibility?: string } & ScopeRef;
    presenceClear: { memberId?: MemberId };
    presencePing: { status?: PresenceStatus };
    presenceUpdate: { status: PresenceStatus; activity?: string; location?: string };
    mediaRoomArchive: { roomId: RoomId };
    mediaRoomCreate: { name: string; allowsVideo?: boolean; group?: null | string; roleAccess?: RoomRoleAccess } & Partial<ScopeRef>;
    mediaRoomJoin: { roomId: RoomId; media?: MediaFlags };
    mediaRoomLeave: { roomId: RoomId };
    mediaRoomUpdate: { roomId: RoomId; locked?: boolean; allowsVideo?: boolean; spotlightMemberId?: string; name?: string; group?: null | string; roleAccess?: RoomRoleAccess };
    screenshareStart: { roomId?: RoomId; title?: string } & ScopeRef;
    screenshareStop: { shareId: ShareId };
    embedAdd: { url: string; title?: string; provider?: string; note?: string } & ScopeRef;
    embedRemove: { embedId: EmbedId };
    reactionToggle: { emoji: string } & ScopeRef;
    directMessageSend: { userIds: MemberId[]; body: string; topicKey?: string };
  }
  export type ActionName = keyof Actions;
  export type ActionPayload<K extends ActionName> = Actions[K];
  export type OperationType = {
    channelArchive: "channel.archive";
    channelCreate: "channel.create";
    channelRename: "channel.rename";
    memberRoleAssign: "member.role.assign";
    messageDelete: "message.delete";
    messageEdit: "message.edit";
    messagePin: "message.pin";
    messageReact: "message.react";
    messageReply: "message.reply";
    messageSend: "message.send";
    messageUnpin: "message.unpin";
    roleArchive: "role.archive";
    roleCreate: "role.create";
    roleUpdate: "role.update";
    commentsAdd: "comments.add";
    commentsDelete: "comments.delete";
    commentsEdit: "comments.edit";
    commentsReact: "comments.react";
    commentsResolve: "comments.resolve";
    commentsThreadCreate: "comments.thread.create";
    presenceClear: "presence.clear";
    presencePing: "presence.ping";
    presenceUpdate: "presence.update";
    mediaRoomArchive: "media.room.archive";
    mediaRoomCreate: "media.room.create";
    mediaRoomJoin: "media.room.join";
    mediaRoomLeave: "media.room.leave";
    mediaRoomUpdate: "media.room.update";
    screenshareStart: "screenshare.start";
    screenshareStop: "screenshare.stop";
    embedAdd: "embed.add";
    embedRemove: "embed.remove";
    reactionToggle: "reaction.toggle";
    directMessageSend: "dm.message";
  };
  export interface Queries {
    channelSummary: Channel[];
    roomDirectory: MediaRoom[];
    onlineMembers: PresenceMember[];
  }
  export type QueryName = keyof Queries;
  export interface QueryInput {
    channelSummary: void;
    roomDirectory: void;
    onlineMembers: void;
  }
  export type RoutePath = "/" | "/dms" | "/rooms";
  export type RouteComponent = "ChatRoomPage" | "DirectMessagesPage" | "MediaRoomsPage";
  export type ConnectionStatus = "connecting" | "connected" | "saving" | "offline" | "error";
  export type DispatchResult = { ok: true; state: State } | { ok: false; reason: string; state?: State };
  export type ActionHelpers = { [K in ActionName]: (payload: Actions[K]) => Promise<DispatchResult>; };
  export interface Core {
    sendPresence(input: { status: PresenceStatus; activity?: string; at?: number }): Promise<boolean>;
  }
  export interface LaunchEnvelope { room?: { id?: string; name?: string }; actor?: Actor; credentialGrant?: { credentialId?: string }; initialState?: State; }
  export interface Client {
    readonly state: State;
    readonly actor: Actor;
    readonly status: ConnectionStatus;
    readonly ready: boolean;
    readonly envelope: LaunchEnvelope;
    readonly message: string;
    readonly lastOperation?: string;
    readonly mediaHost?: unknown;
    readonly actions: ActionHelpers;
    dispatch<K extends ActionName>(action: K, payload: Actions[K]): Promise<DispatchResult>;
    query<K extends QueryName>(name: K, ...input: QueryInput[K] extends void ? [] : [QueryInput[K]]): Queries[K];
    getDMs(topicPattern?: RegExp): DirectMessageThread[];
    subscribeDMs(listener: (threads: DirectMessageThread[]) => void): () => void;
    subscribeDMs(topicPattern: RegExp, listener: (threads: DirectMessageThread[]) => void): () => void;
    refresh(): Promise<State | undefined>;
    core: Core;
  }
}
export interface Chord {
  State: Chord.State;
  Actions: Chord.Actions;
  Queries: Chord.Queries;
  QueryInput: Chord.QueryInput;
  Actor: Chord.Actor;
  Core: Chord.Core;
  LaunchEnvelope: Chord.LaunchEnvelope;
  DispatchResult: Chord.DispatchResult;
  DirectMessageThread: Chord.DirectMessageThread;
  Client: Chord.Client;
}
